name:                aern2-erc
version:             0.2.7.0
github:              "michalkonecny/aern2"
license:             BSD3
author:              "Michal Konecny"
maintainer:          "mikkonecny@gmail.com"
copyright:           "2020-2021 Michal Konecny"

# extra-source-files:
# - README.md
# - changelog.md

# Metadata used when publishing your package
synopsis:            A shallow embedding of ERC into Haskell
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michalkonecny/aern2/#readme>

dependencies:
- base == 4.*
- containers
- transformers
- mtl
- STMonadTrans
- collect-errors >= 0.1.5
- mixed-types-num >= 0.5.8
# - integer-logarithms
- aern2-mp >= 0.2.7

default-extensions:
- PostfixOperators
- DataKinds
- Rank2Types
- FlexibleContexts
- TypeFamilies
- ScopedTypeVariables
- FlexibleInstances

library:
  source-dirs: 
  - src
  ghc-options:
  - -Wall
